name: Run scenario tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# env:
#   AUTH_TOKEN_PROD_RESOURCE_CREATOR: ${{ secrets.AUTH_TOKEN_PROD_RESOURCE_CREATOR }}
#   PROJECT_ROOT_DIR: ${{ github.workspace }}

jobs:
  run-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/k1low/runn
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test
        run: |
          pwd
          runn run runn/hello.yml
