name: Run scenario tests

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Choose Env
        options: 
        - foo
        - hoge

jobs:
  run-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/k1low/runn
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test
        run: |
          AAA=${{ github.event.inputs.env}} runn run runn/a.yml -debug
