name: Test

on:
  workflow_dispatch:
    inputs:
      zone:
        type: choice
        description: Zone
        options:
          - aaa
          - bbb
run-name: Test for ${{ github.event.inputs.zone }}


jobs:
  run-test:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.zone }}
    # env:
    #   FOO=${{ secrets.FOO }}
    steps:
      - name: Run env
        run: |
          echo "${{ secrets.FOO }}"
