name: Test

on:
  workflow_dispatch:
    inputs:
    #   zone:
    #     type: choice
    #     description: Zone
    #     options:
    #       - aaa
    #       - bbb
      zone:
        type: environment
run-name: Test for ${{ github.event.inputs.zone }}

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run env
        env:
          FOO=${{ secrets.FOO }}
        run: |
          echo "${{ env.FOO }}"
