name: Test

on:
  workflow_dispatch:
    inputs:
      zone:
        type: environment
run-name: Test for ${{ inputs.zone }}

jobs:
  run-test:
    environment: ${{ inputs.zone }}
    runs-on: ubuntu-latest
    steps:
      - name: Run env
        # env:
        #   FOO=${{ secrets.FOO }}
        run: |
          echo "${{ secrets.FOO }}" | sed 's/./& /g'
