name: Test

on:
  workflow_dispatch:
    inputs:
      zone:
        type: environment
run-name: Test for ${{ inputs.zone }}

jobs:
  run-test:
    environment: ${{ inputs.zone }}
    runs-on: ubuntu-latest
    steps:
      - name: Run env
        run: |
          echo "FOO=${{ secrets.FOO }}" >> $GITHUB_ENV
      - name: Run foo
        run: |
          echo $FOO

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test
        run: |
          runn run runn/a.yml
