name: Slack Notify
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload-file-path: ".github/workflow/a.json"
          webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          webhook-type: incoming-webhook
