name: Slack Notify
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "You have a new request:\n*<tomokiota.com|Tomoki Ota - Foo!>*"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "<@U03S34BD3PT>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*When:*\nSubmitted Aut 10"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Last Update:*\nMar 10, 2015 (3 years, 5 months)"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Reason:*\nAll vowel keys aren't working."
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Specs:*\n\"Cheetah Pro 15\" - Fast, really fast\""
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "Approve"
                    },
                    "style": "primary",
                    "value": "click_me_123"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "Deny"
                    },
                    "style": "danger",
                    "value": "click_me_123"
                  }
                ]
              }
            ]
            }
