name: Slack Notify
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Failed TEST",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "You have a new request:\n*<tomokiota.com|Tomoki Ota - Foo!>*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*リポジトリ:*\nSubmitted Aut 10"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*実行者:*\n<@U03S34BD3PT>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*ワークフロー:*\n テスト"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*環境:*\n test"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Specs:*\n\"Cheetah Pro 15\" - Fast, really fast\""
                    }
                  ]
                },
                {
                  "type": "rich_text",
                  "elements": [
                    {
                      "type": "rich_text_preformatted",
                      "elements": [
                        {
                          "type": "text",
                          "text": "I am more preformatted text following a quote block"
                        }
                      ]
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "Approve"
                      },
                      "style": "primary",
                      "value": "click_me_123"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "Deny"
                      },
                      "style": "danger",
                      "value": "click_me_123"
                    }
                  ]
                },
                {
                  "type": "rich_text",
                  "elements": [
                    {
                      "type": "rich_text_section",
                      "elements": [
                        {
                          "type": "emoji",
                          "name": "あはは"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
