name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-test:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    container:
      image: golang:latest

    steps:
      # ワークフローの可視化
      - uses: Kesin11/actions-timeline@v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          predicate-quantifier: every
          filters: |
            ignore-paths:
              - "!**.md"
              - "!.vscode/**"
              - "!.devcontainer/**"

      - name: Run test
        if: steps.filter.outputs.ignore-paths == 'true'
        uses: ../.github/workflows/action/

      - name: Save job status
        if: always()
        run: echo "${{ job.status }}" > run-test-status
